version: '3.9' # Versão do compose que interpretará o docker-compose.yml
services:
  backend:
    container_name: bizu-back
    build: ./ # Utilizará o Dockerfile contindo em ./ para gerar a imagem e buildar o container.
    restart: 'always' # Sempre que o serviço parar ele será reiniciado, exceto quando haja interrupção manual.
    ports:
      - 3001:3001 # A API será acessada em localhost:3001.
    depends_on: # backend "depends on" db, ou seja, backend service só será inicializado após db service.
      db:
        condition: service_healthy
    environment: # Definição das variáveis de ambiente (env) do backend.
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - DB_NAME=BIZU_DESIGN_DEV
      - DB_HOST=db # Não será mais localhost e sim o banco MySQL que rodará no container "db", estruturado abaixo.
      - DB_PORT=3306
      - JWT_SECRET=sEgReDiNhO
      - MAIL_TRANSPORT=smtps://jf.pelliccione@gmail.com:vjwxizixvrssymrc@smtp.gmail.com
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.30 # Utilizará a imagem oficial do MySQL, oriunda do Docker Hub, para buildar o container.
    container_name: bizu-db-dev
    ports:
      - 3002:3306 # O banco de dados será acessado na porta 3002.
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Omite alertas menores.